### ISSUE TITLE
Recursive `process.nextTick` crash

### ISSUE THREAD

**Issue by manakor** [thrackle/express-zip#4]
No way to build zip archive (app running on [expressjs](http://expressjs.com)), because `process.nextTick` crashes:
```
RangeError: Maximum call stack size exceeded
```

Here's an error stack:
```
node.js:375
        throw new Error(msg);
              ^ 
Error: (node) warning: Recursive process.nextTick detected.
This will break in the next version of node.
Please use setImmediate for recursive deferral. 
 at maxTickWarn (node.js:375:15)
 at process._nextDomainTick (node.js:498:9)
 at ZipStream._read (node_modules/express-zip/node_modules/zipstream/zipstream.js:80:11)
 at node_modules/express-zip/node_modules/zipstream/zipstream.js:80:38
 at process._tickDomainCallback (node.js:459:13)
```

**Comment by thrackle** [comment]
Fixed in 2.0.0 by #5.
